# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Diagnosis' do

pod 'ObjectiveRecord',      '~> 1.5.0'
pod 'CircleProgressBar',    '~> 0.3’
pod 'AFNetworking',         '~> 3.0.4'
pod 'MBProgressHUD',        '~> 0.9.2'

end

target 'DiagnosisTests' do

pod 'ObjectiveRecord',      '~> 1.5.0'

end

target 'DiagnosisUITests' do

end

